vm_describe might be empty, which triggers a NoMethodError.
==> default: Preparing network interfaces based on configuration...
    default: translation missing: en.vagrant.veertu.network_adapter
{}
==> default: Destroying VM and associated drives...
/Users/snuf/.vagrant.d/gems/2.2.5/gems/vagrant-veertu-0.0.17/lib/vagrant-veertu/driver/version_5_0.rb:281:in `enable_adapters': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/snuf/.vagrant.d/gems/2.2.5/gems/vagrant-veertu-0.0.17/lib/vagrant-veertu/action/network.rb:118:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'